-- 用户DNS解析记录表
CREATE TABLE `user_dns_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `subdomain_id` bigint NOT NULL COMMENT '用户3级域名ID',
  `record_id` bigint DEFAULT NULL COMMENT 'DNSPod记录ID',
  `name` varchar(255) NOT NULL COMMENT '主机记录（如www、mail等，@表示主域名）',
  `type` varchar(20) NOT NULL COMMENT '记录类型（A、CNAME、MX、TXT等）',
  `value` varchar(500) NOT NULL COMMENT '记录值（如IP地址、域名等）',
  `line` varchar(50) NOT NULL DEFAULT '默认' COMMENT '记录线路',
  `line_id` varchar(20) NOT NULL DEFAULT '0' COMMENT '线路ID',
  `ttl` int NOT NULL DEFAULT 600 COMMENT 'TTL值（生存时间）',
  `mx` int DEFAULT NULL COMMENT 'MX优先级（仅MX记录需要）',
  `weight` int DEFAULT NULL COMMENT '权重（负载均衡）',
  `status` varchar(20) NOT NULL DEFAULT 'ENABLE' COMMENT '记录状态（ENABLE或DISABLE）',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注信息',
  `monitor_status` varchar(50) DEFAULT NULL COMMENT '监控状态',
  `updated_on` datetime DEFAULT NULL COMMENT 'DNSPod更新时间',
  `sync_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '同步状态（PENDING-待同步，SUCCESS-同步成功，FAILED-同步失败）',
  `sync_error` text DEFAULT NULL COMMENT '同步错误信息',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_subdomain_name_type` (`user_id`, `subdomain_id`, `name`, `type`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_subdomain_id` (`subdomain_id`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_type` (`type`),
  KEY `idx_status` (`status`),
  KEY `idx_sync_status` (`sync_status`),
  CONSTRAINT `fk_user_dns_record_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_dns_record_subdomain_id` FOREIGN KEY (`subdomain_id`) REFERENCES `user_subdomain` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户DNS解析记录表';